spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/todo}
    username: ${DB_USERNAME:todo}
    password: ${DB_PASSWORD:todo}
    driver-class-name: org.postgresql.Driver
  h2:
    console:
      enabled: false
