create table todos (
    id bigint generated by default as identity primary key,
    title varchar(200) not null,
    description varchar(1000),
    completed boolean not null,
    created_at timestamp not null
);
